# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_language', models.CharField(max_length=20)),
                ('ios_platform', models.BooleanField(default=False)),
                ('android_platform', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('app_sponser_agreed_date', models.DateTimeField(auto_now=True)),
                ('app_sponser_agreed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('netid', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('netid', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('department', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='app_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.Manager'),
        ),
        migrations.AddField(
            model_name='app',
            name='app_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.Sponsor'),
        ),
        migrations.AddField(
            model_name='app',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.App'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.Sponsor'),
        ),
    ]
