# Generated by Django 2.1.15 on 2020-08-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.BooleanField(default=True)),
                ('agree_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_language', models.CharField(max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('netid', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('app_store', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('netid', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=256)),
                ('title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='app_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.Manager'),
        ),
        migrations.AddField(
            model_name='app',
            name='app_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.Sponsor'),
        ),
        migrations.AddField(
            model_name='app',
            name='platform',
            field=models.ManyToManyField(to='mdot.Platform'),
        ),
        migrations.AddField(
            model_name='app',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.App'),
        ),
    ]
