# Generated by Django 2.0.13 on 2021-09-10 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='agree',
        ),
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=models.BooleanField(choices=[(True, 'Agreed'), (False, 'Denied')], default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='netid',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid.', regex='^[a-z][0-9a-z]{0,7}$')]),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='netid',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid.', regex='^[a-z][0-9a-z]{0,7}$')]),
        ),
    ]
