# Generated by Django 2.0.13 on 2021-09-06 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agree',
            field=models.BooleanField(choices=[(True, 'Agreed'), (False, 'Denied')]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='netid',
            field=models.CharField(error_messages={'required': 'Please enter a valid NetID'}, max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid', regex='^[a-z][0-9a-z]{0,7}$')]),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='netid',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid', regex='^[a-z][0-9a-z]{0,7}$')]),
        ),
    ]
