# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_sponser_agreed',
            new_name='app_sponsor_agreed',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_sponser_agreed_date',
        ),
        migrations.RemoveField(
            model_name='app',
            name='requestor',
        ),
    ]
