# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='requester',
        ),
    ]
