# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0002_auto_20200114_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='netid',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='netid',
            field=models.CharField(max_length=16),
        ),
    ]
