# Generated by Django 2.0.13 on 2021-09-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0002_auto_20210910_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.BooleanField(
                choices=[(True, 'Agreed'), (False, 'Denied')]),
        ),
    ]
