# Generated by Django 2.0.13 on 2021-09-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0002_auto_20210907_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='agree',
            new_name='agreement_status',
        ),
    ]
