# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0002_remove_app_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='android_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='ios_platform',
            field=models.BooleanField(default=False),
        ),
    ]
