# Generated by Django 2.0.13 on 2021-09-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0003_manager_to_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='to_app',
        ),
    ]
