# Generated by Django 2.1.15 on 2020-08-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0003_auto_20200629_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agree',
            field=models.BooleanField(default=True),
        ),
    ]
