# Generated by Django 2.0.13 on 2021-09-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0003_auto_20210907_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement_status',
            new_name='status',
        ),
    ]
