# Generated by Django 2.0.13 on 2021-09-10 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0003_auto_20210910_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('agreed', 'Agreed'), ('denied', 'Denied'), ('removed', 'Removed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='netid',
            field=models.CharField(error_messages={'required': 'Please enter a valid NetID'}, max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid.', regex='^[a-z][0-9a-z]{0,7}$')]),
        ),
    ]
