# Generated by Django 2.0.13 on 2021-09-25 00:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0004_auto_20210910_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdot.App')),
            ],
        ),
        migrations.AlterField(
            model_name='manager',
            name='netid',
            field=models.CharField(error_messages={'required': 'Please enter a valid NetID'}, max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid.', regex='^[a-z][a-z0-9\\-\\_\\.]{,127}$')]),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='netid',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid.', regex='^[a-z][a-z0-9\\-\\_\\.]{,127}$')]),
        ),
    ]
