# Generated by Django 2.0.13 on 2021-09-25 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0004_auto_20210910_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='netid',
            field=models.CharField(error_messages={'required': 'Please enter a valid NetID'}, max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid.', regex='^[a-z][a-z0-9\\-\\_\\.]{,127}$')]),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='netid',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='NetID must be valid.', regex='^[a-z][a-z0-9\\-\\_\\.]{,127}$')]),
        ),
    ]
