# Generated by Django 2.0.13 on 2021-09-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0005_auto_20210902_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='corresp_app',
            new_name='app',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_agreement',
        ),
    ]
