# Generated by Django 2.0.13 on 2021-09-03 00:26

from django.db import migrations, models
import mdot.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0006_auto_20210903_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_agreement',
            field=models.CharField(
                default='<property object at 0x7f8d0a16ae08>',
                editable=False,
                max_length=150,
                verbose_name=mdot.models.Agreement
            ),
        ),
    ]
