# Generated by Django 3.2.8 on 2021-10-13 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
