# Generated by Django 2.0.13 on 2021-09-03 02:15

from django.db import migrations, models
import mdot.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdot', '0007_app_app_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agree',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_agreement',
            field=models.CharField(
                default='<property object at 0x7ff487887d18>',
                editable=False,
                max_length=150,
                verbose_name=mdot.models.Agreement
            ),
        ),
    ]
